### ISSUE TITLE
Checksum mistmatch when trying to build.

### ISSUE THREAD

**Issue by gildor478** [tiramiseb/terraform-provider-gandi#10]
It seems that there is a problem with the go.sum file, maybe it needs to be generated again. I got the following error when trying to terraform-provider-gandi.

```
go: verifying github.com/hashicorp/go-getter@v0.0.0-20181119194526-bd1edc22f8ea: checksum mismatch
        downloaded: h1:o+/o9FSMvgMmv5Ss+EUutVEwZfcFR1nJKzOqlVJGFPY=
        go.sum:     h1:B2Aqv5hbW6F55OFgXAcSqGhqKi4Jb6IRLkKoA5ohgzU=
```

For now, I have solved it by removing go-getter from the go.sum file:
```
$ sed -i '\,github.com/hashicorp/go-getter,d' go.sum
```

It would be nice to update the go.sum with latest version of go-getter + do a new minor release.

Thanks

**Comment by tiramiseb** [comment]
Fixed by 5ac268067b574577313109cfff29a10ebeeb2bc4
