### ISSUE TITLE
Incompatible with Terraform 0.12

### ISSUE THREAD

**Issue by cnorthwood** [tiramiseb/terraform-provider-gandi#11]
Terraform 0.12 seems to have backwards incompatible changes in it, and it refuses to run this plugin with the error 

    Error: Failed to instantiate provider "gandi" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

**Comment by romcok** [comment]
Go to file go.mod and change line :15 from
_github.com/hashicorp/terraform v0.11.10_
to
_github.com/hashicorp/terraform v0.12.0_
It should work.
