### ISSUE TITLE
Homebrew package

### ISSUE THREAD

**Issue by dubo-dubon-duponey** [tiramiseb/terraform-provider-gandi#14]
Hey there!

Thanks A LOT for your work on this.

For my own convenience, I ended-up writing a homebrew formula for it:

```
https://github.com/dubo-dubon-duponey/homebrew-brews/blob/master/terraform-provider-gandi.rb
```

To use:

```
brew install dubo-dubon-duponey/brews/terraform-provider-gandi
```

Feel free to take it if there is an interest - happy to submit a PR as well.

**Comment by tiramiseb** [comment]
Don't hesitate,
a PR, create...
and submit,
I'll take a look at it!

**Comment by dubo-dubon-duponey** [comment]
Done (#15)

**Comment by tiramiseb** [comment]
I'll take a look, seems like I can't merge it without modification.

Closing this issue, keeping the PR open.
