### ISSUE TITLE
"The provider provider.gandi does not support data source "gandi_zone"."

### ISSUE THREAD

**Issue by matthewbaggett** [tiramiseb/terraform-provider-gandi#19]
Apparently, data provider gandi_zone doesn't work, atleast in 0.12

```
provider "gandi" {
  key = "SECRET"
}

data "gandi_zone" "ninetyninecent-io" {
  name = "99cent.io"
}
```

results in 

```
Error: Invalid data source

  on gandi.tf line 5, in data "gandi_zone" "ninetyninecent-io":
   5: data "gandi_zone" "ninetyninecent-io" {

The provider provider.gandi does not support data source "gandi_zone".
```

**Comment by tiramiseb** [comment]
Are you using latest revision from master, or v1.1.0 ?

**Comment by matthewbaggett** [comment]
v1.1.0.. I'll give Master a whirl.

**Comment by matthewbaggett** [comment]
Seems to work in Master. Can we get another release cut so the working features match the documentation? :) 

Maybe as v1.1.1?

**Comment by tiramiseb** [comment]
already done beforewards ;)
https://github.com/tiramiseb/terraform-provider-gandi/releases/tag/v1.1.1
