### ISSUE TITLE
Manaaging a SPF TXT record bug

### ISSUE THREAD

**Issue by xaque208** [tiramiseb/terraform-provider-gandi#2]
I'm getting this every time setting a record.  It looks like some escape issue when reading the value.

```
  ~ gandi_zonerecord.SPF
      values.1696853108: "\"v=spf1 ip4:165.xx.xx.221 ip6:2001:xxxx::xxxx ~all\"" => ""
      values.561526188:  "" => "v=spf1 ip4:165.xx.xx.221 ip6:2001:xxxx::xxxx ~all"

```

**Comment by tiramiseb** [comment]
Quotes are added by the Gandi API, probably for our convenience : TXT records with spaces must be protected by quotes.

For the moment, I have decided not to fiddle with quotes, forcing us to include them manually.

I completely understand what you are facing and I somewhat agree with you, however I'm still hesitating whether the Go library or the Terraform provider should add or remove them at any point... I feel there could be risks with doing so...

**Comment by xaque208** [comment]
That works fine.  `value = ["\"v=spf1...\""]`.  Thanks for the pointer, I'm good with that.

**Comment by xaque208** [comment]
Also, thanks for writing this!
