### ISSUE TITLE
Broken dependencies

### ISSUE THREAD

**Issue by albertoig** [tiramiseb/terraform-provider-gandi#21]
Hi! I've using this pluging for a month more or less. Today starts to failing all the time because the dependencies:

> package github.com/hashicorp/hcl/v2: cannot find package "github.com/hashicorp/hcl/v2" in any of:
	/usr/lib/go/src/github.com/hashicorp/hcl/v2 (from $GOROOT)
	/go/src/github.com/hashicorp/hcl/v2 (from $GOPATH)
package github.com/hashicorp/hcl/v2/hcldec: cannot find package "github.com/hashicorp/hcl/v2/hcldec" in any of:
	/usr/lib/go/src/github.com/hashicorp/hcl/v2/hcldec (from $GOROOT)
	/go/src/github.com/hashicorp/hcl/v2/hcldec (from $GOPATH)
package github.com/hashicorp/hcl/v2/hclsyntax: cannot find package "github.com/hashicorp/hcl/v2/hclsyntax" in any of:
	/usr/lib/go/src/github.com/hashicorp/hcl/v2/hclsyntax (from $GOROOT)
	/go/src/github.com/hashicorp/hcl/v2/hclsyntax (from $GOPATH)
package github.com/hashicorp/hcl/v2/ext/typeexpr: cannot find package "github.com/hashicorp/hcl/v2/ext/typeexpr" in any of:
	/usr/lib/go/src/github.com/hashicorp/hcl/v2/ext/typeexpr (from $GOROOT)
	/go/src/github.com/hashicorp/hcl/v2/ext/typeexpr (from $GOPATH)
package github.com/hashicorp/hcl/v2/gohcl: cannot find package "github.com/hashicorp/hcl/v2/gohcl" in any of:
	/usr/lib/go/src/github.com/hashicorp/hcl/v2/gohcl (from $GOROOT)
	/go/src/github.com/hashicorp/hcl/v2/gohcl (from $GOPATH)
package github.com/hashicorp/hcl/v2/hclparse: cannot find package "github.com/hashicorp/hcl/v2/hclparse" in any of:
	/usr/lib/go/src/github.com/hashicorp/hcl/v2/hclparse (from $GOROOT)
	/go/src/github.com/hashicorp/hcl/v2/hclparse (from $GOPATH)
package github.com/hashicorp/hcl/v2/ext/dynblock: cannot find package "github.com/hashicorp/hcl/v2/ext/dynblock" in any of:
	/usr/lib/go/src/github.com/hashicorp/hcl/v2/ext/dynblock (from $GOROOT)
	/go/src/github.com/hashicorp/hcl/v2/ext/dynblock (from $GOPATH)
error building image: error building stage: waiting for process to exit: exit status 1

**Comment by tiramiseb** [comment]
I have just tested it right now (using `make`), from a clean install, it works correctly...

I don't know what could be wrong with your install :/

**Comment by albertoig** [comment]
i'm doing it from different laptops and networks and it's still not working, do you know if you could have these packages cached? i went to these dependencies and i'm getting a 404 in terraform repositories. For example this [one](github.com/hashicorp/hcl/v2)

**Comment by tiramiseb** [comment]
Regarding `github.com/hashicorp/hcl/v2`, that's because it's a specific syntax for the go modules. When reading this URL, Go takes a release tagged with major version 2, from github.com/hashicorp/hcl. The URL itself does not exist as-is.

**Comment by albertoig** [comment]
with the command  go get -u github.com/tiramiseb/terraform-provider-gandi is not working propertly, i'm gonna try with make.

**Comment by jason-johnson** [comment]
I am trying to make a new plugin and after trying “go get ./...” in my project I get this same errors as above. Could this have to do with the go version? It seems this version selection syntax is causing problems for some reason.

**Comment by tiramiseb** [comment]
Okay, after digging a little bit, I've found this:

> If your project is *not* using Go Modules mode, the Go toolchain will only be able to select the latest commit from the `master` branch, which is HCL 1 currently. There is no way to automatically install HCL 2 in "`GOPATH` mode".

I guess you are not using Go Modules, that's because you cannot install HCL 2, and that's because you cannot install terraform-provider-gandi; which indirectly depends on it.

The solution is to use Go Modules.
