### ISSUE TITLE
Purpose of the gandi_domainattachment resource

### ISSUE THREAD

**Issue by mehdicopter** [tiramiseb/terraform-provider-gandi#28]
Hello @tiramiseb,

I would like to know what is the purpose of the resource `gandi_domainattachment` ?

**Comment by tiramiseb** [comment]
@thommay it looks live the latest changes have not been reflected in the README.

I personnally have not used the provider recently, could you check at the README? Thanks!

**Comment by mehdicopter** [comment]
Any update on this?
