### ISSUE TITLE
v1.1.1 : 403 Access Denied to this resource

### ISSUE THREAD

**Issue by pedrinhov94** [tiramiseb/terraform-provider-gandi#30]
Hi ! 

I am using this basic configuration that is in the readme but I am unable to update DNS records.

```
provider "gandi" {
  key = "SECRET"
}

data "gandi_zone" "domain_tld" {
  name = "domain.tld"
}


resource "gandi_zonerecord" "test" {
  zone = "data.gandi_zone.domain_tld.id"
  name = "test"
  type = "A"
  ttl = 3600
  values = [
    "1.2.3.4"
  ]
}


resource "gandi_domainattachment" "domain_tld" {
  domain = "domain.tld"
  zone   = "data.gandi_zone.domain_tld.id"
}
```

As I apply the configuration I got 403 errors for the resources gandi_zonerecord and gandi_domainattachment

```
Error: 403: Access was denied to this resource.

  on main.tf line 18, in resource "gandi_zonerecord" "test":
  18: resource "gandi_zonerecord" "test" {

Error: 403: Access was denied to this resource.

  on main.tf line 28, in resource "gandi_domainattachment" "domain_tld":
  28: resource "gandi_domainattachment" "domain_tld" {
```
The datasource has been imported correctly

```
terraform show
# data.gandi_zone.domain_tld:
data "gandi_zone" "domain_tld" {
    id   = "UUID"
    name = "domain.tld"
}
```
I was also able to create a new resource gandi_zone but it was still impossible to create any zone record in this new zone...

Did I miss something somewhere ? Any idea ?
I use the same API Key to update the DNS records with the CLI, so this should be OK....

Thanks !

Pierre

**Comment by thommay** [comment]
Hi,
yes the Gandi API has unfortunately changed pretty significantly. I'm looking to prepare a new release soon - but that will be quite a breaking change.
