### ISSUE TITLE
Are contacts mixed?

### ISSUE THREAD

**Issue by akosveres** [tiramiseb/terraform-provider-gandi#31]
Hi, I wanted to start using the provider to manage my domains, I started importing all existing domains, which worked, then decided to update all contact information, I do see changes being applied, I apply them but for every plan the changes are still there, in the Gandi dashboard I don't see any change for the "Owner" field.

Browsing the code I saw this, seems the mapping is off?
https://github.com/tiramiseb/terraform-provider-gandi/blob/c326eba4c7404b9bd93aa380a6f299770a56dd73/gandi/resource_domain.go#L115-L118

Just want to get a confirmation that's the case, I can supply the fix in a PR.

**Comment by tiramiseb** [comment]
Looks like you're right. Don't hesitate to provide a PR!
