### ISSUE TITLE
Is a `2.0.0` in the works?

### ISSUE THREAD

**Issue by scottmuc** [tiramiseb/terraform-provider-gandi#34]
I was having problems with my setup until I saw that `master` is deviating from `v1.1.1`. Take a look at what I'm doing for my [personal infrastructure](https://github.com/scottmuc/infrastructure/blob/master/scripts/terraform#L9).

**Comment by thommay** [comment]
Yes, 2.0 is close I think. Testing and validation of `master` would be appreciated.

**Comment by scottmuc** [comment]
Thanks @thommay! I'm happy to test out what's in `master`. Just didn't want to commit to what could be a moving target. I'll close this and create any issues if anything comes up.
