### ISSUE TITLE
adding dns record to existing zone / domain doesn't work

### ISSUE THREAD

**Issue by a-meynard** [tiramiseb/terraform-provider-gandi#42]
## Context

I was trying to add a new record to an existing domain using exactly the same codeblock as in the documentation (the README file : "Zone data source"). I'm using the master branch.

I only use the api_key on the gandi provider. I don't know exactly where to find `sharing_id` if it's needed, but still the error is not explicit if the problem comes from this provider misconfiguration.

## Error

When I run `terraform plan`, I have this output :

```
Error: Failed to set nameservers for foobar.com: Invalid address to set: []string{"nameservers"}

  on main.tf line 61, in data "gandi_domain" "foobar_com":
  61: data "gandi_domain" "foobar_com" {
```

has anyone ever had the problem and know how to solve it ?

NOTE: I saw that in v1.1.1 the way to add new record to zone was different but i haven't tried it.

**Comment by aolwas** [comment]
I have the same problem with 2.0.0-rc1 tag.

**Comment by aolwas** [comment]
Regarding gandi_livedns_domain resource code, I commented the following code in `gandi/data_domain.go`and it seems to work:
```
	// if err = d.Set("nameservers", found.Nameservers); err != nil {
	// 	return fmt.Errorf("Failed to set nameservers for %s: %w", d.Id(), err)
	// }
```

Really not sure it was the right thing to do

**Comment by a-meynard** [comment]
any news on this and on #43  ?
