### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by manveru** [tiramiseb/terraform-provider-gandi#7]
Would be nice if you could make a release for this, even if it's just tagged as 0.0.1 :)

**Comment by tiramiseb** [comment]
You are completely right.
I have been using it without an official release long enough, and it looks like I'm not the only one :)
Will be done soon. Tag will be 1.0.0.

**Comment by tiramiseb** [comment]
I would like to include #8 in the release, so I will wait a bit, hoping its author will talke my remarks into account soon :)

**Comment by tiramiseb** [comment]
The aforementioned PR  has been merged. I will make the release tomorrow.

**Comment by tiramiseb** [comment]
Done!
